### ISSUE TITLE
KeyError: "['hospitaladmityear'] not in index"

### ISSUE THREAD

**Issue by PiasTanmoy** [mostafaalishahi/eICU_Benchmark#5]
Traceback (most recent call last):
  File "data_extraction_root.py", line 51, in <module>
    main()
  File "data_extraction_root.py", line 49, in main
    data_extraction_root(args)
  File "data_extraction_root.py", line 16, in data_extraction_root
    patients = utils.read_patients_table(args.eicu_dir, args.output_dir)
  File "/home/danfeng/LLM-HC/eICU/eICU_Benchmark/data_extraction/utils.py", line 82, in read_patients_table
    pats = filter_patients_on_columns(pats)
  File "/home/danfeng/LLM-HC/eICU/eICU_Benchmark/data_extraction/utils.py", line 119, in filter_patients_on_columns
    return patients[columns]
  File "/home/danfeng/LLM-HC/eICU/.venv3.5/lib/python3.5/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/home/danfeng/LLM-HC/eICU/.venv3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/home/danfeng/LLM-HC/eICU/.venv3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/home/danfeng/LLM-HC/eICU/.venv3.5/lib/python3.5/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['hospitaladmityear'] not in index"

My virtual environment is (Python 3.5.10)

Package         Version
--------------- -----------
joblib          0.14.1
numpy           1.15.0
pandas          0.24.1
pip             20.3.4
python-dateutil 2.9.0.post0
pytz            2024.1
scikit-learn    0.21.2
scipy           1.2.0
setuptools      50.3.2
six             1.16.0
wheel           0.37.1

**Comment by mostafaalishahi** [comment]
for any reasons, you do not have 'hospitaladmityear' column in your data. Either you could check your data or you just drop this column hospitaladmityear as it is not being used anywhere in the next steps.
